server {
    listen 80;
    server_name localhost;

    # Proxy ke aplikasi FastAPI (pdf-app)
    location / {
        proxy_pass http://pdf-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Izinkan ukuran upload file besar (misal max 50MB)
        client_max_body_size 50M;
    }
}
